/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface HimoButton {
    }
    interface HimoTabs {
        "className": string;
        "size": string;
        "tabList": Array<any>;
        "type": string;
    }
}
export interface HimoTabsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHimoTabsElement;
}
declare global {
    interface HTMLHimoButtonElement extends Components.HimoButton, HTMLStencilElement {
    }
    var HTMLHimoButtonElement: {
        prototype: HTMLHimoButtonElement;
        new (): HTMLHimoButtonElement;
    };
    interface HTMLHimoTabsElement extends Components.HimoTabs, HTMLStencilElement {
    }
    var HTMLHimoTabsElement: {
        prototype: HTMLHimoTabsElement;
        new (): HTMLHimoTabsElement;
    };
    interface HTMLElementTagNameMap {
        "himo-button": HTMLHimoButtonElement;
        "himo-tabs": HTMLHimoTabsElement;
    }
}
declare namespace LocalJSX {
    interface HimoButton {
    }
    interface HimoTabs {
        "className"?: string;
        "onChange"?: (event: HimoTabsCustomEvent<any>) => void;
        "onTabClick"?: (event: HimoTabsCustomEvent<any>) => void;
        "size"?: string;
        "tabList"?: Array<any>;
        "type"?: string;
    }
    interface IntrinsicElements {
        "himo-button": HimoButton;
        "himo-tabs": HimoTabs;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "himo-button": LocalJSX.HimoButton & JSXBase.HTMLAttributes<HTMLHimoButtonElement>;
            "himo-tabs": LocalJSX.HimoTabs & JSXBase.HTMLAttributes<HTMLHimoTabsElement>;
        }
    }
}
